import { Input } from "@/components/ui/input";
import { Check, ChevronDown, ChevronUp, X } from "lucide-react";
import React from "react";
import { toast } from "@/components/ui/use-toast";
import { useNavigate } from "react-router-dom";
import { Textarea } from "@/components/ui/textarea";

// Form Component
interface TestData {
  ticketCode: string;
  totalQuantity: number;
  assemblyAno: string;
  source: string;
  otherSource: string; // New field for "Other" source
  reason: string;
  project: string;
  build: string;
  colour: string;
  dateTime: string;
  status: string;
}

const SOURCE_OPTIONS = ["Entire", "Line1", "Line2", "Other"];
const PROJECT_OPTIONS = ["FLASH", "LIGHT", "HULK", "AQUA"];
const BUILD_OPTIONS = ["J713", "J813", "N230", "N240"];
const COLOUR_OPTIONS = ["NDA", "LIGHT BLUE"];
const REASON_OPTIONS = [
  "Line qualification",
  "Machine qualification",
  "MP",
  "NPI",
  "Other"
];

// Type for tracking next numbers per project
interface ProjectCounter {
  [key: string]: number;
}

const TestForm: React.FC = () => {
  const navigate = useNavigate();
  const [formData, setFormData] = React.useState<TestData>({
    ticketCode: "",
    totalQuantity: 0,
    assemblyAno: "",
    source: "",
    otherSource: "",
    reason: "",
    project: "",
    build: "",
    colour: "",
    dateTime: "",
    status: "In-Progress"
  });
  
  const [showOtherSource, setShowOtherSource] = React.useState(false);

  // Load existing data and set today's date
  React.useEffect(() => {
    const today = new Date().toISOString().split("T")[0];
    setFormData(prev => ({
      ...prev,
      dateTime: today
    }));

    // Load existing records to log them
    const storedData = localStorage.getItem("testRecords");
    if (storedData) {
      try {
        const parsedData = JSON.parse(storedData);
        console.log("Existing records loaded:", parsedData);
        console.log("Total records count:", parsedData.length);
      } catch (error) {
        console.error("Error parsing stored data:", error);
      }
    } else {
      console.log("No existing records found in localStorage");
    }
  }, []);

  // Generate ticket code when project changes
  React.useEffect(() => {
    if (formData.project) {
      generateTicketCode(formData.project);
    }
  }, [formData.project]);

  // Show/hide other source input
  React.useEffect(() => {
    setShowOtherSource(formData.source === "Other");
    
    // Clear otherSource if source is not "Other"
    if (formData.source !== "Other") {
      setFormData(prev => ({
        ...prev,
        otherSource: ""
      }));
    }
  }, [formData.source]);

  const generateTicketCode = (project: string) => {
    // Get existing records
    const storedData = localStorage.getItem("testRecords");
    let records: any[] = [];
    
    if (storedData) {
      try {
        records = JSON.parse(storedData);
        if (!Array.isArray(records)) {
          records = [];
        }
      } catch (error) {
        console.error("Error parsing existing records:", error);
        records = [];
      }
    }

    // Filter records for the selected project
    const projectRecords = records.filter(record => 
      record.project === project
    );

    // Get the highest ticket number for this project
    let maxNumber = 0;
    projectRecords.forEach(record => {
      const match = record.ticketCode?.match(new RegExp(`^${project}-(\\d+)$`));
      if (match) {
        const num = parseInt(match[1], 10);
        if (num > maxNumber) {
          maxNumber = num;
        }
      }
    });

    // Generate next ticket code
    const nextNumber = maxNumber + 1;
    const ticketCode = `${project}-${nextNumber.toString().padStart(3, '0')}`;

    setFormData(prev => ({
      ...prev,
      ticketCode
    }));
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    
    // Handle number input specifically
    if (name === "totalQuantity") {
      setFormData(prev => ({
        ...prev,
        [name]: value === "" ? 0 : parseInt(value, 10)
      }));
    } else if (name === "project") {
      // When project changes, update form data
      setFormData(prev => ({
        ...prev,
        [name]: value,
        // Ticket code will be auto-generated by the useEffect
      }));
    } else {
      setFormData(prev => ({
        ...prev,
        [name]: value
      }));
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    try {
      // Determine final source value
      const finalSource = formData.source === "Other" 
        ? formData.otherSource 
        : formData.source;

      // Validate required fields
      if (!formData.ticketCode || !formData.totalQuantity || !formData.source || 
          !formData.reason || !formData.project || !formData.build || 
          !formData.colour || !formData.dateTime) {
        toast({
          variant: "destructive",
          title: "Validation Error",
          description: "Please fill all required fields marked with *",
          duration: 3000,
        });
        return;
      }

      // Additional validation for "Other" source
      if (formData.source === "Other" && !formData.otherSource.trim()) {
        toast({
          variant: "destructive",
          title: "Validation Error",
          description: "Please specify the source when 'Other' is selected",
          duration: 3000,
        });
        return;
      }

      // Get existing data from localStorage
      const existingData = localStorage.getItem("testRecords");
      let records = [];
      
      if (existingData) {
        try {
          records = JSON.parse(existingData);
          // Ensure it's an array
          if (!Array.isArray(records)) {
            records = [];
          }
        } catch (error) {
          console.error("Error parsing existing records:", error);
          records = [];
        }
      }

      const currentDate = new Date().toISOString().split("T")[0];

      // Create new record with combined source
      const newRecord = {
        ...formData,
        source: finalSource, // Use the combined source value
        dateTime: currentDate,
        id: Date.now(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      };

      records.push(newRecord);

      // Save back to localStorage
      localStorage.setItem("testRecords", JSON.stringify(records));

      console.log("Record saved successfully:", newRecord);
      console.log("Total records now:", records.length);

      // Reset form
      setFormData({
        ticketCode: "",
        totalQuantity: 0,
        assemblyAno: "",
        source: "",
        otherSource: "",
        reason: "",
        project: "",
        build: "",
        colour: "",
        dateTime: "",
        status: "In-Progress"
      });

      // Success toast
      toast({
        title: "✅ Record Created",
        description: `Ticket ${newRecord.ticketCode} has been saved successfully!`,
        duration: 3000,
      });

      // Navigate to barcode-scanner after a short delay
      setTimeout(() => {
        navigate("/barcode-scanner", {
          state: {
            record: newRecord,
            allRecords: records
          }
        });
      }, 1000);

    } catch (error) {
      console.error("Error saving test data:", error);
      toast({
        variant: "destructive",
        title: "Save Failed",
        description: "There was an error saving the test data. Please try again.",
        duration: 3000,
      });
    }
  };

  // Helper function to view all records (for debugging)
  const viewAllRecords = () => {
    const storedData = localStorage.getItem("testRecords");
    if (storedData) {
      const records = JSON.parse(storedData);
      console.log("=== ALL STORED RECORDS ===");
      console.log("Total:", records.length);
      
      // Group by project for debugging
      const projectGroups: {[key: string]: any[]} = {};
      records.forEach((record: any) => {
        if (!projectGroups[record.project]) {
          projectGroups[record.project] = [];
        }
        projectGroups[record.project].push(record);
      });
      
      console.log("Records by project:", projectGroups);
      
      toast({
        title: "Records Logged",
        description: `Found ${records.length} records. Check console for details.`,
        duration: 2000,
      });
    } else {
      console.log("No records found in localStorage");
      toast({
        title: "No Records",
        description: "No records found in localStorage",
        duration: 2000,
      });
    }
  };

  // Helper function to clear all records (for debugging)
  const clearAllRecords = () => {
    if (window.confirm("Are you sure you want to clear ALL records? This cannot be undone.")) {
      localStorage.removeItem("testRecords");
      console.log("All records cleared from localStorage");
      toast({
        variant: "destructive",
        title: "Records Cleared",
        description: "All records have been removed from localStorage.",
        duration: 3000,
      });
      
      // Reset ticket code if project is selected
      if (formData.project) {
        generateTicketCode(formData.project);
      }
    }
  };

  return (
    <div className="max-w-6xl mx-auto mt-6">
      <div className="px-6 py-4">
        <div className="flex justify-between items-center mb-6">
          <h1 className="text-2xl font-bold">Test Data Form</h1>
          {/* Debug buttons - uncomment if needed */}
          {/* <div className="flex gap-2">
            <button
              type="button"
              onClick={viewAllRecords}
              className="text-xs px-3 py-1 border border-gray-300 rounded hover:bg-gray-100"
              title="View all stored records in console"
            >
              View Records ({(() => {
                const stored = localStorage.getItem("testRecords");
                return stored ? JSON.parse(stored).length : 0;
              })()})
            </button>
            <button
              type="button"
              onClick={clearAllRecords}
              className="text-xs px-3 py-1 border border-red-300 text-red-600 rounded hover:bg-red-50"
              title="Clear all records"
            >
              Clear All
            </button>
          </div> */}
        </div>

        <form onSubmit={handleSubmit} className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {/* Ticket Code - Auto-generated and read-only */}
            <div className="space-y-2">
              <label className="block text-sm font-bold text-slate-800 mb-3 uppercase tracking-wide">
                Ticket Code <span className="text-red-600">*</span>
                <span className="text-xs font-normal text-gray-500 ml-2">(Auto-generated)</span>
              </label>
              <Input
                type="text"
                name="ticketCode"
                value={formData.ticketCode}
                readOnly
                className="h-14 px-5 border-2 border-slate-300 rounded-xl font-medium text-slate-700 bg-gray-50"
                placeholder="Select project to generate code"
              />
              
            </div>

            {/* Total Quantity */}
            <div className="space-y-2">
              <label className="block text-sm font-bold text-slate-800 mb-3 uppercase tracking-wide">
                Total Quantity <span className="text-red-600">*</span>
              </label>
              <Input
                type="number"
                name="totalQuantity"
                value={formData.totalQuantity || ""}
                onChange={handleInputChange}
                placeholder="Enter total quantity"
                className="h-14 px-5 border-2 border-slate-300 rounded-xl font-medium text-slate-700 placeholder:text-slate-400 focus:border-blue-500 focus:ring-4 focus:ring-blue-100 transition-all shadow-sm"
                required
                min="1"
              />
            </div>

            {/* Assembly/Ano */}
            <div className="space-y-2">
              <label className="block text-sm font-bold text-slate-800 mb-3 uppercase tracking-wide">
                Assembly/Ano <span className="text-red-600">*</span>
              </label>
              <Input
                type="text"
                name="assemblyAno"
                value={formData.assemblyAno}
                onChange={handleInputChange}
                placeholder="Auto filled based on RBAC admin access"
                className="h-14 px-5 border-2 border-slate-300 rounded-xl font-medium text-slate-700 placeholder:text-slate-400 focus:border-blue-500 focus:ring-4 focus:ring-blue-100 transition-all shadow-sm"
                required
              />
            </div>

            {/* Source (entire/line1/line2/other) */}
            <div className="space-y-2">
              <label className="block text-sm font-bold text-slate-800 mb-3 uppercase tracking-wide">
                Source <span className="text-red-600">*</span>
              </label>
              <select
                name="source"
                value={formData.source}
                onChange={handleInputChange}
                className="h-14 w-full px-5 border-2 border-slate-500 rounded-xl font-medium text-slate-700 focus:border-blue-500 focus:ring-4 focus:ring-blue-100 transition-all shadow-sm bg-white appearance-none pr-10"
                required
              >
                <option value="">-- Select Source --</option>
                {SOURCE_OPTIONS.map((option) => (
                  <option key={option} value={option}>
                    {option}
                  </option>
                ))}
              </select>

              {/* Other Source Input (conditionally shown) */}
              {showOtherSource && (
                <div className="mt-2">
                  <Input
                    type="text"
                    name="otherSource"
                    value={formData.otherSource}
                    onChange={handleInputChange}
                    placeholder="Please specify source"
                    className="h-12 px-4 border-2 border-slate-300 rounded-lg font-medium text-slate-700 placeholder:text-slate-400 focus:border-blue-500 focus:ring-2 focus:ring-blue-100 transition-all"
                    required={formData.source === "Other"}
                  />
                </div>
              )}
            </div>

            {/* Project */}
            <div className="space-y-2">
              <label className="block text-sm font-bold text-slate-800 mb-3 uppercase tracking-wide">
                Project <span className="text-red-600">*</span>
              </label>
              <select
                name="project"
                value={formData.project}
                onChange={handleInputChange}
                className="h-14 w-full px-5 border-2 border-slate-500 rounded-xl font-medium text-slate-700 focus:border-blue-500 focus:ring-4 focus:ring-blue-100 transition-all shadow-sm bg-white appearance-none pr-10"
                required
              >
                <option value="">-- Select Project --</option>
                {PROJECT_OPTIONS.map((option) => (
                  <option key={option} value={option}>
                    {option}
                  </option>
                ))}
              </select>
            </div>

            {/* Build - Manual Entry (now as text input instead of select) */}
            <div className="space-y-2">
              <label className="block text-sm font-bold text-slate-800 mb-3 uppercase tracking-wide">
                Build <span className="text-red-600">*</span>
                <span className="text-xs font-normal text-gray-500 ml-2">(Manual entry)</span>
              </label>
              <Input
                type="text"
                name="build"
                value={formData.build}
                onChange={handleInputChange}
                placeholder="Enter build"
                className="h-14 px-5 border-2 border-slate-300 rounded-xl font-medium text-slate-700 placeholder:text-slate-400 focus:border-blue-500 focus:ring-4 focus:ring-blue-100 transition-all shadow-sm"
                required
              />
            </div>

            {/* Colour */}
            <div className="space-y-2">
              <label className="block text-sm font-bold text-slate-800 mb-3 uppercase tracking-wide">
                Colour <span className="text-red-600">*</span>
              </label>
              <select
                name="colour"
                value={formData.colour}
                onChange={handleInputChange}
                className="h-14 w-full px-5 border-2 border-slate-500 rounded-xl font-medium text-slate-700 focus:border-blue-500 focus:ring-4 focus:ring-blue-100 transition-all shadow-sm bg-white appearance-none pr-10"
                required
              >
                <option value="">-- Select Colour --</option>
                {COLOUR_OPTIONS.map((option) => (
                  <option key={option} value={option}>
                    {option}
                  </option>
                ))}
              </select>
            </div>

            {/* Date Time */}
            <div className="space-y-2">
              <label className="block text-sm font-bold text-slate-800 mb-5 uppercase tracking-wide">
                Date Time <span className="text-red-600">*</span>
              </label>
              <Input
                type="date"
                name="dateTime"
                value={formData.dateTime}
                readOnly
                className="h-14 px-5 border-2 border-slate-300 rounded-xl font-medium text-slate-700 placeholder:text-slate-400 focus:border-blue-500 focus:ring-4 focus:ring-blue-100 transition-all shadow-sm"
              />
            </div>

            {/* Reason */}
            <div className="space-y-2">
              <label className="block text-sm font-bold text-slate-800 mb-3 uppercase tracking-wide">
                Reason <span className="text-red-600">*</span>
              </label>
              <select
                name="reason"
                value={formData.reason}
                onChange={handleInputChange}
                className="h-14 w-full px-5 border-2 border-slate-500 rounded-xl font-medium text-slate-700 focus:border-blue-500 focus:ring-4 focus:ring-blue-100 transition-all shadow-sm bg-white appearance-none pr-10"
                required
              >
                <option value="">-- Select Reason --</option>
                {REASON_OPTIONS.map((option) => (
                  <option key={option} value={option}>
                    {option}
                  </option>
                ))}
              </select>
            </div>
          </div>

          <div className="flex justify-end gap-4">
            <button
              type="submit"
              className="flex items-center w-fit border rounded-full bg-[#f35b62] text-white py-2 px-4 hover:bg-[#EE161F] hover:text-white transition-colors"
            >
              <Check className="w-5 h-5 mr-2" />
              <span>Submit & Continue</span>
            </button>
          </div>
        </form>

        {/* Debug Info Panel - uncomment if needed */}
        {/* <div className="mt-8 p-4 border border-gray-200 rounded-lg bg-gray-50">
          <h3 className="font-semibold text-gray-700 mb-2">Debug Information</h3>
          <div className="text-sm text-gray-600 space-y-1">
            <p>Current form data:</p>
            <pre className="bg-white p-2 rounded border text-xs overflow-auto">
              {JSON.stringify(formData, null, 2)}
            </pre>
            <p>LocalStorage key: <code className="bg-gray-100 px-1 rounded">testRecords</code></p>
            <p>Records count: <strong>{(() => {
              const stored = localStorage.getItem("testRecords");
              return stored ? JSON.parse(stored).length : 0;
            })()}</strong></p>
          </div>
        </div> */}
      </div>
    </div>
  );
};

export default TestForm;